@startuml
actor QuizTaker
participant QuizController
participant QuestionIterator
participant Grader
participant AnswerKey
QuizController -> QuestionStore: iterator()
'QuestionIterator -> AnswerKey: saveAnswer("q1", "map")
QuestionIterator -> QuizController: question content
QuizController -> QuizTaker: The Question Form
QuizTaker -> QuizController: Submit Answer ("q1", "response")
QuizController -> Grader: answer("q1", "response")
Grader -> AnswerKey
@enduml